export const GET_LAUNCH_POINTS = "GET_LAUNCH_POINTS";
export const ADD_LAUNCH_POINT = "ADD_LAUNCH_POINT";
export const REMOVE_LAUNCH_POINT = "REMOVE_LAUNCH_POINT";
export const SWAP_LAUNCH_POINT = "SWAP_LAUNCH_POINT";
export const RUNNING_APPS = 'RUNNING_APPS';
export const SHOW_APP = 'SHOW_APP';
export const APP_BAR_ALIGN = 'APP_BAR_ALIGN';
export const APP_BAR_SHOW = 'APP_BAR_SHOW';
export const SORT_TYPE_UPDATE = 'SORT_TYPE_UPDATE';

export const APP_BAR_NAMES = 'APP_BAR_NAMES';
export const APP_BAR_NAME_DELETE = 'APP_BAR_NAME_DELETE';
export const CHANGE_APP_BAR_VIEW = 'CHANGE_APP_BAR_VIEW';
export const SEARCH_NAME_UPDATE = 'SEARCH_NAME_UPDATE';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SEARCH_STRING = 'SEARCH_STRING';
//Alert Types
export const DELETE_APP = 'DELETE_APP';
export const MAX_APPADD_LIMIT = 'MAX_APPADD_LIMIT';

//Drag Types
export const SET_DRAGGING = 'SET_DRAGGING';
export const SET_DROP_HIGHLIGHT = 'SET_DROP_HIGHLIGHT';
export const CLEAR_DRAG = 'CLEAR_DRAG';

//Edit
export const SET_LAUNCHPAD_EDIT = 'SET_LAUNCHPAD_EDIT';
export const CLEAR_LAUNCHPAD_EDIT = 'CLEAR_LAUNCHPAD_EDIT';
export const SET_APPBAR_EDIT = 'SET_APPBAR_EDIT';
export const CLEAR_APPBAR_EDIT = 'CLEAR_APPBAR_EDIT';
export const CLEAR_EDIT = 'CLEAR_EDIT';

//Feedback
export const SHOW_FEEDBACK = 'SHOW_FEEDBACK';
export const HIDE_FEEDBACK = 'HIDE_FEEDBACK';

